# -*- coding: utf-8 -*-
"""Generates reports/survivorship.md from the actual data."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import pandas as pd
from src import config as C
from src.universe import validate_identity, tradable_universe

memb = pd.read_parquet(C.DATA_PROC / "membership_utilities.parquet")
close = pd.read_parquet(C.DATA_PROC / "prices_adj.parquet")
val, tu = validate_identity(memb, close), tradable_universe(memb, close)
lost = sorted(set(memb.columns) - set(tu.columns))
slots_all, slots_kept = int(memb.values.sum()), int(tu.values.sum())
per = pd.DataFrame({"raw": memb.sum(axis=1), "tradable": tu.sum(axis=1)})
per["lost"] = per.raw - per.tradable
worst = per[per.lost > 0]
pairs = lambda n: n * (n - 1) // 2

notes = {
 "GAS": "AGL Resources, acquired by Southern Company (2016). No data served: outright loss.",
 "NU":  "Northeast Utilities, **renamed Eversource (ES)** in 2015. Ticker reused since 2021 by "
        "Nu Holdings (Brazilian neobank). Only an apparent loss: the ES series goes back to 2014 "
        "and carries the history.",
 "POM": "Pepco Holdings, acquired by Exelon (2016). Ticker recycled in 2025.",
 "TE":  "TECO Energy, acquired by Emera (2016). Ticker recycled in 2020.",
 "TEG": "Integrys Energy, acquired by WEC (2015). Ticker recycled in late 2015.",
}

L = []
L.append("# Survivorship bias, quantification and direction\n")
L.append("Generated by `scripts/build_survivorship_en.py`. Source: `reports/identity_validation.csv`.")
L.append("French version: `reports/survivorship.md`.\n")
L.append("## 1. What point-in-time fixes\n")
L.append("Index membership is read from the Wikipedia page **as it existed** on each selection")
L.append("date (25 semi-annual snapshots, 2-day median lag). The screener therefore never sees a")
L.append("name before it entered the index, nor after it left.\n")
L.append("The clearest case: **PCG (PG&E)** is out of the index from 2019-07 to 2022-07 , ")
L.append("Chapter 11 after the Camp Fire, removal, then readmission. A universe built on")
L.append("**current** constituents would include PCG and trade it through the bankruptcy,")
L.append("knowing it came out alive. Point-in-time excludes it automatically.\n")
L.append("## 2. What remains uncorrected\n")
L.append(f"Raw union: **{memb.shape[1]} tickers**. Tradable universe: **{tu.shape[1]}**.")
L.append(f"Excluded: **{len(lost)}** ({', '.join(lost)}).\n")
L.append("| Ticker | Member snapshots | Status | Reason |")
L.append("|---|---|---|---|")
for t in lost:
    L.append(f"| `{t}` | {int(memb[t].sum())} | {val.loc[t,'status']} | {notes[t]} |")
L.append("")
L.append("All of these exits are **index removals by acquisition** (no bankruptcy).\n")
L.append("## 3. Magnitude\n")
L.append(f"- Membership slots (snapshot x ticker): {slots_all} raw, {slots_kept} kept "
         f"→ **{100*(slots_all-slots_kept)/slots_all:.1f} % lost**.")
L.append("- Losses are concentrated in 2014-2016; from 2019-07 onward they are zero.\n")
L.append("| Snapshot | Sector (raw) | Tradable | Lost | Testable pairs |")
L.append("|---|---|---|---|---|")
for d, r in worst.iterrows():
    L.append(f"| {d:%Y-%m} | {int(r.raw)} | {int(r.tradable)} | {int(r.lost)} | "
             f"{pairs(int(r.raw))} → {pairs(int(r.tradable))} |")
L.append("")
L.append("**Order of magnitude.** Losses are entirely concentrated in the first six snapshots")
L.append("(2014-01 to 2016-07) and **zero from 2017-01**. At the worst snapshot (2014-01), 5 names")
L.append("are missing out of 31, 16 % of the universe, i.e. 1-(26/31)^2 ≈ **30 % of potential")
L.append("pairs** untestable. From 2017 the residual survivorship on composition is nil.\n")
L.append("Practical consequence for the walk-forward: the first fold (selection 2014-2016) is the")
L.append("most exposed. An honest option is to report its result separately rather than silently")
L.append("aggregating it with the others.\n")
L.append("## 4. Direction of the bias\n")
L.append("The five lost names all left the index **by acquisition**. A takeover is precisely the")
L.append("event that breaks a cointegration relation most brutally: the target's price jumps to")
L.append("the offer price and then freezes, permanently decorrelated from its sector. A short")
L.append("position on the target at announcement takes an instant, non-mean-reverting loss.\n")
L.append("**Consequence: their exclusion Overstates the strategy's performance.** The bias runs")
L.append("in the favourable direction, which is the most dangerous case, it never announces")
L.append("itself.\n")
L.append("## 5. Limits of the reconstruction itself\n")
L.append("- Wikipedia is edited with a lag of a few days (median 2 d, max 19 d here). No effect at")
L.append("  an annual re-selection cadence.")
L.append("- **EVRG** (Evergy, formed in 2018 from the Westar/Great Plains merger) has vendor")
L.append("  history back to 2014: those are the predecessor's prices. Legitimate, but worth noting.")
L.append("- The identity check rests on the overlap between quotation and membership. It would")
L.append("  less reliably catch a ticker recycling occurring *during* the membership window, a")
L.append("  case not observed here.")
(C.Reports / "survivorship.md").write_text("\n".join(L), encoding="utf-8")
print("written -> reports/survivorship.md")
